CREATE TABLE IF NOT EXISTS countries (
    id INT PRIMARY KEY AUTO_INCREMENT,
    country VARCHAR(60) NOT NULL UNIQUE
);

INSERT INTO countries (country) VALUES ('Afghanistan');
INSERT INTO countries (country) VALUES ('Albania');
INSERT INTO countries (country) VALUES ('Algeria');
INSERT INTO countries (country) VALUES ('Andorra');
INSERT INTO countries (country) VALUES ('Angola');
INSERT INTO countries (country) VALUES ('Antigua and Barbuda');
INSERT INTO countries (country) VALUES ('Argentina');
INSERT INTO countries (country) VALUES ('Armenia');
INSERT INTO countries (country) VALUES ('Australia');
INSERT INTO countries (country) VALUES ('Austria');
INSERT INTO countries (country) VALUES ('Azerbaijan');
INSERT INTO countries (country) VALUES ('The Bahamas');
INSERT INTO countries (country) VALUES ('Bahrain');
INSERT INTO countries (country) VALUES ('Bangladesh');
INSERT INTO countries (country) VALUES ('Barbados');
INSERT INTO countries (country) VALUES ('Belarus');
INSERT INTO countries (country) VALUES ('Belgium');
INSERT INTO countries (country) VALUES ('Belize');
INSERT INTO countries (country) VALUES ('Benin');
INSERT INTO countries (country) VALUES ('Bhutan');
INSERT INTO countries (country) VALUES ('Bolivia');
INSERT INTO countries (country) VALUES ('Bosnia and Herzegovina');
INSERT INTO countries (country) VALUES ('Botswana');
INSERT INTO countries (country) VALUES ('Brazil');
INSERT INTO countries (country) VALUES ('Brunei');
INSERT INTO countries (country) VALUES ('Bulgaria');
INSERT INTO countries (country) VALUES ('Burkina Faso');
INSERT INTO countries (country) VALUES ('Burundi');
INSERT INTO countries (country) VALUES ('Cabo Verde');
INSERT INTO countries (country) VALUES ('Cambodia');
INSERT INTO countries (country) VALUES ('Cameroon');
INSERT INTO countries (country) VALUES ('Canada');
INSERT INTO countries (country) VALUES ('Central African Republic');
INSERT INTO countries (country) VALUES ('Chad');
INSERT INTO countries (country) VALUES ('Chile');
INSERT INTO countries (country) VALUES ('China');
INSERT INTO countries (country) VALUES ('Colombia');
INSERT INTO countries (country) VALUES ('Comoros');
INSERT INTO countries (country) VALUES ('Congo, Democratic Republic of the');
INSERT INTO countries (country) VALUES ('Congo, Republic of the');
INSERT INTO countries (country) VALUES ('Costa Rica');
INSERT INTO countries (country) VALUES ('Côte d’Ivoire');
INSERT INTO countries (country) VALUES ('Croatia');
INSERT INTO countries (country) VALUES ('Cuba');
INSERT INTO countries (country) VALUES ('Cyprus');
INSERT INTO countries (country) VALUES ('Czech Republic');
INSERT INTO countries (country) VALUES ('Denmark');
INSERT INTO countries (country) VALUES ('Djibouti');
INSERT INTO countries (country) VALUES ('Dominica');
INSERT INTO countries (country) VALUES ('Dominican Republic');
INSERT INTO countries (country) VALUES ('East Timor (Timor-Leste)');
INSERT INTO countries (country) VALUES ('Ecuador');
INSERT INTO countries (country) VALUES ('Egypt');
INSERT INTO countries (country) VALUES ('El Salvador');
INSERT INTO countries (country) VALUES ('Equatorial Guinea');
INSERT INTO countries (country) VALUES ('Eritrea');
INSERT INTO countries (country) VALUES ('Estonia');
INSERT INTO countries (country) VALUES ('Eswatini');
INSERT INTO countries (country) VALUES ('Ethiopia');
INSERT INTO countries (country) VALUES ('Fiji');
INSERT INTO countries (country) VALUES ('Finland');
INSERT INTO countries (country) VALUES ('France');
INSERT INTO countries (country) VALUES ('Gabon');
INSERT INTO countries (country) VALUES ('The Gambia');
INSERT INTO countries (country) VALUES ('Georgia');
INSERT INTO countries (country) VALUES ('Germany');
INSERT INTO countries (country) VALUES ('Ghana');
INSERT INTO countries (country) VALUES ('Greece');
INSERT INTO countries (country) VALUES ('Grenada');
INSERT INTO countries (country) VALUES ('Guatemala');
INSERT INTO countries (country) VALUES ('Guinea');
INSERT INTO countries (country) VALUES ('Guinea-Bissau');
INSERT INTO countries (country) VALUES ('Guyana');
INSERT INTO countries (country) VALUES ('Haiti');
INSERT INTO countries (country) VALUES ('Honduras');
INSERT INTO countries (country) VALUES ('Hungary');
INSERT INTO countries (country) VALUES ('Iceland');
INSERT INTO countries (country) VALUES ('India');
INSERT INTO countries (country) VALUES ('Indonesia');
INSERT INTO countries (country) VALUES ('Iran');
INSERT INTO countries (country) VALUES ('Iraq');
INSERT INTO countries (country) VALUES ('Ireland');
INSERT INTO countries (country) VALUES ('Israel');
INSERT INTO countries (country) VALUES ('Italy');
INSERT INTO countries (country) VALUES ('Jamaica');
INSERT INTO countries (country) VALUES ('Japan');
INSERT INTO countries (country) VALUES ('Jordan');
INSERT INTO countries (country) VALUES ('Kazakhstan');
INSERT INTO countries (country) VALUES ('Kenya');
INSERT INTO countries (country) VALUES ('Kiribati');
INSERT INTO countries (country) VALUES ('Korea, North');
INSERT INTO countries (country) VALUES ('Korea, South');
INSERT INTO countries (country) VALUES ('Kosovo');
INSERT INTO countries (country) VALUES ('Kuwait');
INSERT INTO countries (country) VALUES ('Kyrgyzstan');
INSERT INTO countries (country) VALUES ('Laos');
INSERT INTO countries (country) VALUES ('Latvia');
INSERT INTO countries (country) VALUES ('Lebanon');
INSERT INTO countries (country) VALUES ('Lesotho');
INSERT INTO countries (country) VALUES ('Liberia');
INSERT INTO countries (country) VALUES ('Libya');
INSERT INTO countries (country) VALUES ('Liechtenstein');
INSERT INTO countries (country) VALUES ('Lithuania');
INSERT INTO countries (country) VALUES ('Luxembourg');
INSERT INTO countries (country) VALUES ('Madagascar');
INSERT INTO countries (country) VALUES ('Malawi');
INSERT INTO countries (country) VALUES ('Malaysia');
INSERT INTO countries (country) VALUES ('Maldives');
INSERT INTO countries (country) VALUES ('Mali');
INSERT INTO countries (country) VALUES ('Malta');
INSERT INTO countries (country) VALUES ('Marshall Islands');
INSERT INTO countries (country) VALUES ('Mauritania');
INSERT INTO countries (country) VALUES ('Mauritius');
INSERT INTO countries (country) VALUES ('Mexico');
INSERT INTO countries (country) VALUES ('Micronesia, Federated States of');
INSERT INTO countries (country) VALUES ('Moldova');
INSERT INTO countries (country) VALUES ('Monaco');
INSERT INTO countries (country) VALUES ('Mongolia');
INSERT INTO countries (country) VALUES ('Montenegro');
INSERT INTO countries (country) VALUES ('Morocco');
INSERT INTO countries (country) VALUES ('Mozambique');
INSERT INTO countries (country) VALUES ('Myanmar (Burma)');
INSERT INTO countries (country) VALUES ('Namibia');
INSERT INTO countries (country) VALUES ('Nauru');
INSERT INTO countries (country) VALUES ('Nepal');
INSERT INTO countries (country) VALUES ('Netherlands');
INSERT INTO countries (country) VALUES ('New Zealand');
INSERT INTO countries (country) VALUES ('Nicaragua');
INSERT INTO countries (country) VALUES ('Niger');
INSERT INTO countries (country) VALUES ('Nigeria');
INSERT INTO countries (country) VALUES ('North Macedonia');
INSERT INTO countries (country) VALUES ('Norway');
INSERT INTO countries (country) VALUES ('Oman');
INSERT INTO countries (country) VALUES ('Pakistan');
INSERT INTO countries (country) VALUES ('Palau');
INSERT INTO countries (country) VALUES ('Panama');
INSERT INTO countries (country) VALUES ('Papua New Guinea');
INSERT INTO countries (country) VALUES ('Paraguay');
INSERT INTO countries (country) VALUES ('Peru');
INSERT INTO countries (country) VALUES ('Philippines');
INSERT INTO countries (country) VALUES ('Poland');
INSERT INTO countries (country) VALUES ('Portugal');
INSERT INTO countries (country) VALUES ('Qatar');
INSERT INTO countries (country) VALUES ('Romania');
INSERT INTO countries (country) VALUES ('Russia');
INSERT INTO countries (country) VALUES ('Rwanda');
INSERT INTO countries (country) VALUES ('Saint Kitts and Nevis');
INSERT INTO countries (country) VALUES ('Saint Lucia');
INSERT INTO countries (country) VALUES ('Saint Vincent and the Grenadines');
INSERT INTO countries (country) VALUES ('Samoa');
INSERT INTO countries (country) VALUES ('San Marino');
INSERT INTO countries (country) VALUES ('Sao Tome and Principe');
INSERT INTO countries (country) VALUES ('Saudi Arabia');
INSERT INTO countries (country) VALUES ('Senegal');
INSERT INTO countries (country) VALUES ('Serbia');
INSERT INTO countries (country) VALUES ('Seychelles');
INSERT INTO countries (country) VALUES ('Sierra Leone');
INSERT INTO countries (country) VALUES ('Singapore');
INSERT INTO countries (country) VALUES ('Slovakia');
INSERT INTO countries (country) VALUES ('Slovenia');
INSERT INTO countries (country) VALUES ('Solomon Islands');
INSERT INTO countries (country) VALUES ('Somalia');
INSERT INTO countries (country) VALUES ('South Africa');
INSERT INTO countries (country) VALUES ('Spain');
INSERT INTO countries (country) VALUES ('Sri Lanka');
INSERT INTO countries (country) VALUES ('Sudan');
INSERT INTO countries (country) VALUES ('Sudan, South');
INSERT INTO countries (country) VALUES ('Suriname');
INSERT INTO countries (country) VALUES ('Sweden');
INSERT INTO countries (country) VALUES ('Switzerland');
INSERT INTO countries (country) VALUES ('Syria');
INSERT INTO countries (country) VALUES ('Taiwan');
INSERT INTO countries (country) VALUES ('Tajikistan');
INSERT INTO countries (country) VALUES ('Tanzania');
INSERT INTO countries (country) VALUES ('Thailand');
INSERT INTO countries (country) VALUES ('Togo');
INSERT INTO countries (country) VALUES ('Tonga');
INSERT INTO countries (country) VALUES ('Trinidad and Tobago');
INSERT INTO countries (country) VALUES ('Tunisia');
INSERT INTO countries (country) VALUES ('Turkey');
INSERT INTO countries (country) VALUES ('Turkmenistan');
INSERT INTO countries (country) VALUES ('Tuvalu');
INSERT INTO countries (country) VALUES ('Uganda');
INSERT INTO countries (country) VALUES ('Ukraine');
INSERT INTO countries (country) VALUES ('United Arab Emirates');
INSERT INTO countries (country) VALUES ('United Kingdom');
INSERT INTO countries (country) VALUES ('United States');
INSERT INTO countries (country) VALUES ('Uruguay');
INSERT INTO countries (country) VALUES ('Uzbekistan');
INSERT INTO countries (country) VALUES ('Vanuatu');
INSERT INTO countries (country) VALUES ('Vatican City');
INSERT INTO countries (country) VALUES ('Venezuela');
INSERT INTO countries (country) VALUES ('Vietnam');
INSERT INTO countries (country) VALUES ('Yemen');
INSERT INTO countries (country) VALUES ('Zambia');
INSERT INTO countries (country) VALUES ('Zimbabwe');