package io.github.mateusznk.webankapp.errors;

public enum TypesOfErrors {
    USERNAME_IS_TAKEN,
    USERNAME_IS_NOT_VALID,
    PASSWORD_NOT_MEET_REQUIREMENTS,
    GIVEN_PASSWORDS_DO_NOT_MATCH,
    EMAIL_IS_NOT_VALID,
    CONDITIONS_NOT_ACCEPTED,
    USER_TOO_YOUNG
}
